spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: ad
    password: ad
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: h2
    generate-ddl: true
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true